CREATE Type statuses as enum ('ACTIVE','DELETED');

CREATE TABLE status (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status statuses NOT NULL,
    CONSTRAINT unique_status UNIQUE(status)
);