create TABLE developers (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName varchar(255) NOT NULL,
    lastName varchar(255) NOT NULL,
    specialty integer NOT NULL,
    status integer NOT NULL,
    CONSTRAINT developers_fk0
    FOREIGN KEY (specialty) REFERENCES specialties(id),
    CONSTRAINT developers_fk1
    FOREIGN KEY (status) REFERENCES status(id)
);